# Generated by Django 5.0.6 on 2026-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=200)),
                ('short_summary', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('affected_assets', models.JSONField(default=list)),
                ('affected_sectors', models.JSONField(default=list)),
                ('sentiment', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', max_length=10)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('supporting_articles', models.ManyToManyField(blank=True, to='news.article')),
            ],
            options={
                'ordering': ['-generated_at', '-confidence_score'],
            },
        ),
    ]
